version: '3.6'

services:

  srvdb:
    image: postgres
    container_name: srvdb
    hostname: srvdb
    environment:
      POSTGRES_USER: test
      POSTGRES_DB: test
      POSTGRES_PASSWORD: test.123
    ports:
      - 5432:5432